#Name of the workflow.
name: Sample eShopOnWeb dot net workflow

#Workflow starts when below events occurs. Ex. code pushed to main branch or pull_request raised to main branch.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#Set of Job(s) runs for the event. Ex. build is a job.
jobs:
  build:

#Environment(s) used to run. Ex.ubuntu, mac-os, windows.
    runs-on: ubuntu-latest

#Set of step(s) for the job(ex. build)
    steps:
    
    #Checkout the code. uses opensource action (https://github.com/actions/checkout)
    - uses: actions/checkout@v2
    
    #To Set up dotnet 5.0 environment using opensource action (https://github.com/actions/setup-dotnet)
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    #To resolve application dependencies.
    - name: Install dependencies 
      run: dotnet restore 

    #To build dotnet application using MSBuild
    - name: Build
      run: dotnet msbuild ./eShopOnWeb.sln
      
    #To Run application tests
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --no-build --verbosity normal
    
    #To Packackage dotnet Application
    - name: Package
      run: dotnet pack ./eShopOnWeb.sln --configuration Release
      
    #To Add nuget artifacts repository as source to push artifacts.
    - name: AddSource
      run: dotnet nuget add source "https://nuget.pkg.github.com/tamilselvansellamuthu/index.json" -n "github" 
      
    #To Push nuget package to artifacts repository using GitHub Secrets.
    - name: Push
      run: dotnet nuget push "bin/Release/*.nupkg"  --api-key ${{ secrets.TOKEN_GITHUB }} --source "github"
